language: node_js
node_js:
    - '12' # EOL: April 2022
    - '10' # EOL: April 2021

jobs:
    include:
        - stage: deploy
          node_js: "lts/*"
          script: skip
          before_deploy: if [ "$TRAVIS_BRANCH" = master ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm version prerelease --no-git-tag-version --preid "$TRAVIS_BUILD_NUMBER"; fi
          deploy:
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: CiuL/soTffuanT3pxRIDWpTWXRVaAYbU6n++qqbLa34iPBgUsDjUjesVRaN9fEXygzHzA17VX9buWVNn7+V0RPjX4beERvjRxghLnhd1W7f7+AH72+QMnSzj7CUcBeraRMggfzL8umV9/6uuHLAvJZYkn/2gAkS7nAPMqNS/uU2oU/C/RJgfKhOLxxUPh8SELUwdc37AG81KWG6fEfLhtdJcuzqA3aTE+qR+E5kb6v3zqHYpXlKIKU8yysIL8hMxW4IDbb8FEISOi1oac76uunPKYREkz5/gkcIpMUjoXcgajzp1tGWNTLc/okFtYp9po0zjZDpql4ZVfYnRpSevnJfp62Oe3DNHYzIy20ptJ+2SHfP1wLfUWIbbT+m+vhc+UxBUm+a5uhNQMpH/woapgrNLVejIi1XjOKvZQStSqaZzVM2BTov+dPNlqfUHYkttwzasiqJOlxX7Ww3tTQJ0zMB+QZYXsDRlaleM8ZnzzXgRHEn+0x1F8tO7eWx/rfZBEyTrmt9prgb9AvTVz/oY2hr7ySAkhvku3tA9c+g3ROH/dLxTvSeldYOkva7S4CB3oGpleksGnQKbdDEuk61Z1yA3a0iay9d0Z8xUi+Cx2xEEQm3kChR1e7+ZijMrJHA37YJORYSKOw0cvJHWsfghxAxzzeBp9vVSWuiTvJnGkJU=
                tag: next
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/micro-web-service
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: CiuL/soTffuanT3pxRIDWpTWXRVaAYbU6n++qqbLa34iPBgUsDjUjesVRaN9fEXygzHzA17VX9buWVNn7+V0RPjX4beERvjRxghLnhd1W7f7+AH72+QMnSzj7CUcBeraRMggfzL8umV9/6uuHLAvJZYkn/2gAkS7nAPMqNS/uU2oU/C/RJgfKhOLxxUPh8SELUwdc37AG81KWG6fEfLhtdJcuzqA3aTE+qR+E5kb6v3zqHYpXlKIKU8yysIL8hMxW4IDbb8FEISOi1oac76uunPKYREkz5/gkcIpMUjoXcgajzp1tGWNTLc/okFtYp9po0zjZDpql4ZVfYnRpSevnJfp62Oe3DNHYzIy20ptJ+2SHfP1wLfUWIbbT+m+vhc+UxBUm+a5uhNQMpH/woapgrNLVejIi1XjOKvZQStSqaZzVM2BTov+dPNlqfUHYkttwzasiqJOlxX7Ww3tTQJ0zMB+QZYXsDRlaleM8ZnzzXgRHEn+0x1F8tO7eWx/rfZBEyTrmt9prgb9AvTVz/oY2hr7ySAkhvku3tA9c+g3ROH/dLxTvSeldYOkva7S4CB3oGpleksGnQKbdDEuk61Z1yA3a0iay9d0Z8xUi+Cx2xEEQm3kChR1e7+ZijMrJHA37YJORYSKOw0cvJHWsfghxAxzzeBp9vVSWuiTvJnGkJU=
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/micro-web-service
                    tags: true
